_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
batch_size:
    value: 256
l1_lambda:
    value: 1e-09
l2_lambda:
    value: 1e-10
lr:
    value: 0.001
model:
    value: LSTMModel
num_epochs:
    value: 1
